// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJRaoaPPsTOK1coLFkLf8Su3Qvl5J0Uis',
    appId: '1:1034676646302:web:ef20a15c5f7bdc8f34268f',
    messagingSenderId: '1034676646302',
    projectId: 'chama-chapa',
    authDomain: 'chama-chapa.firebaseapp.com',
    storageBucket: 'chama-chapa.firebasestorage.app',
    measurementId: 'G-NKW3BFL39V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_CWHk2MaGegqUBa40ZL8vRmKTsdPsGY',
    appId: '1:1034676646302:android:08a7d123d6c8ce6334268f',
    messagingSenderId: '1034676646302',
    projectId: 'chama-chapa',
    storageBucket: 'chama-chapa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIt2fSKyVL7hrm5Ya8-aDDGwBxCUvmFQs',
    appId: '1:1034676646302:ios:b1b484318329024f34268f',
    messagingSenderId: '1034676646302',
    projectId: 'chama-chapa',
    storageBucket: 'chama-chapa.firebasestorage.app',
    iosBundleId: 'com.example.chamaChapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIt2fSKyVL7hrm5Ya8-aDDGwBxCUvmFQs',
    appId: '1:1034676646302:ios:b1b484318329024f34268f',
    messagingSenderId: '1034676646302',
    projectId: 'chama-chapa',
    storageBucket: 'chama-chapa.firebasestorage.app',
    iosBundleId: 'com.example.chamaChapa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJRaoaPPsTOK1coLFkLf8Su3Qvl5J0Uis',
    appId: '1:1034676646302:web:62490cab61d74e5a34268f',
    messagingSenderId: '1034676646302',
    projectId: 'chama-chapa',
    authDomain: 'chama-chapa.firebaseapp.com',
    storageBucket: 'chama-chapa.firebasestorage.app',
    measurementId: 'G-S5XH2X7KT2',
  );
}
